### ISSUE TITLE
qTox closes when changing profile is cancelled

### ISSUE THREAD

**Issue by tux3** [dubslow/qTox#4]
After qTox is started, switching to an encrypted profile and canceling can cause qTox to close without explanation.

Repro:
- Have an encrypted and an unencrypted profile
- Switch to the unencrypted profile
- Click change profile at the password prompt
- Click cancel at the change profile prompt-
- qTox closes with "Core: loadConfiguration failed, exiting now" in log

**Comment by dubslow** [comment]
This is the misdesign I mentioned that I was working on

**Comment by dubslow** [comment]
@tux3 @zetok Could one of you test the fix please? I can can compile but not actually run qTox until Sunday.

As well as testing that it works, you should also test that it works several times in succession, that it works from different "original" profiles in the same run of qTox (which should also cover making successful switches to various profiles and then canceling again).

**Comment by tux3** [comment]
Will do.

**Comment by tux3** [comment]
This is not fixed as of 0470b5a6af984964ebc9f7429dce77b8cfe3e172 (current HEAD)

The steps described in the OP still reproduce the bug.

**Comment by dubslow** [comment]
I'd bet $10 that the fix works except for some minor logic detail I overlooked while writing the code. Unfortunately, there's no real way I can try and find it...

Would you be willing to throw in some print statements in the areas in the diff and let me know what comes out? That or it'll just have to wait until Sunday.

**Comment by tux3** [comment]
@dubslow 
I ran it in a debugger. By the time we're in Settings::getInstance().switchProfile(profile) in the else branch, the main() has returned, entered Widget::~Widget, and is std::terminate'ing us (because I spent too long on a breakpoint in the debugger, so it stopped waiting for the Core thread and just killed it).

**Comment by tux3** [comment]
Actually, by the time loadConfiguration(loadPath) returns, it's already in the Widget destructor.

**Comment by dubslow** [comment]
wtf? That's the same crap that @zetok had?

Now I'm massively confused.

**Comment by tux3** [comment]
Hrm. I don't want to be That Guy, but there's a big <h3>qApp->quit();</h3> in Widget::askProfiles ...

**Comment by dubslow** [comment]
I don't think that's related? You don't see that dialog, it appears either at startup or when loading the Tox file fails due to encryption (and no password yet).

So that's unrelated to history?

**Comment by dubslow** [comment]
Before I saw these, I was gonna ask about 
```
diff --git a/src/coreencryption.cpp b/src/coreencryption.cpp
index 9821cac..08a41f0 100644
--- a/src/coreencryption.cpp
+++ b/src/coreencryption.cpp
@@ -79,6 +79,7 @@ void Core::saveCurrentInformation()
         backupkeys[ptHistory] = new uint8_t[tox_pass_key_length()];
         std::copy(pwsaltedkeys[ptHistory], pwsaltedkeys[ptHistory]+tox_pass_key_length(), backupkeys[ptHistory]);
     }
+    qDebug() << "Core: saving information of profile" << Settings::getInstance().getCurrentProfile();
     backupProfile = new QString(Settings::getInstance().getCurrentProfile());
 }
 
@@ -100,6 +101,7 @@ QString Core::loadOldInformation()
     pwsaltedkeys[ptHistory] = backupkeys[ptHistory];
     backupkeys[ptMain]    = nullptr;
     backupkeys[ptHistory] = nullptr;
+    qDeubg() << "Core: loaded old information of profile" << out << ", should be loading back to it now after canceling";
     return out;
 }
```

May be useful still... I have no idea what's going on here

**Comment by tux3** [comment]
Yes, it's very related. This is what causes qTox to exit when you click Cancel :
![image8](https://cloud.githubusercontent.com/assets/5155966/5930351/b2c46d32-a68e-11e4-955a-11ca5cb605f4.jpg)

And it's called by Core here :
![image9](https://cloud.githubusercontent.com/assets/5155966/5930361/cc7dc6ce-a68e-11e4-8d25-780b0aeb9e60.jpg)

The problem is very clear. That function has no business calling qApp->quit, what the hell ?

**Comment by dubslow** [comment]
Here's hoping you didn't read the comments I just posted. I was getting myself horribly mixed up. Yeah, that's probably an issue lol.

When that function was written, it was used only on startup (or at least that's what I was thinking). Obviously that's no longer the case (if it ever was).

**Comment by tux3** [comment]
Alright, glad we found the fix :)

Do you want to write write a fix in here or should I send a PR ?

**Comment by dubslow** [comment]
Already pushed :)

**Comment by dubslow** [comment]
Just to be clear, can you confirm that this is now fixed?

**Comment by tux3** [comment]
Yes, this is fixed.
