### ISSUE TITLE
Encrypted history can get corrupted and disabled if password prompt is closed

### ISSUE THREAD

**Issue by tux3** [dubslow/qTox#5]
If the history password prompt is closed, qTox will fail to decrypt history, disable it, and corrupt it.
Messages like "Core::decryptData: decryption failed", "EncryptedDb::pullFileContent: Encrypted history log is corrupted: can't decrypt, will be deleted", and "Core: can't get salt from "/home/mlkj/.config/tox/Tux3.qtox_history.encrypted" header" appear in the log.

Repro:
- Have an encrypted profile, both profile and history.
- Restart, enter your profile password
- Close the history password prompt (DO NOT click on a button, close it)
- Decryption fails silently, history gets corrupted and disabled

**Comment by dubslow** [comment]
Close...? You can close the password prompt? Oh man. Do you right click on the title bar or something?

**Comment by tux3** [comment]
Note: The same happens if the "bad history password, try again" box is closed.

@dubslow that windows is closable. There is a "red cross" in the title bar.

**Comment by dubslow** [comment]
I do not have any buttons of any sort in the title bar.

**Comment by tux3** [comment]
Pressing "Escape" at the password prompt seems to have the same effect as closing it.

**Comment by tux3** [comment]
With the fix above applied, history is no longer corrupted and can be used again after being re-enabled, but it is still deleted if the dialog box is closed, so the issue is not fixed.

**Comment by dubslow** [comment]
Hmm okay trying to think about it some more after a few hours. I'm reading this comment, and it doesn't make sense to me. The dialog box has to be closed in some way or another, which you say deletes the history, but then you also say it isn't deleted and can be used again. (Boy I wish I could test it myself lol)

**Comment by tux3** [comment]
It isn't corrupted anymore. Before, it would get corrupted and when you tried to enable it again you couldn't.
Now it's just deleted. If you re-enable it, you lost it (it's deleted) but you can make it work again (it's not corrupted).

It shouldn't get corrupted (that's fixed) and it shouldn't be deleted either (that's NOT fixed) when you close that dialog box.

**Comment by dubslow** [comment]
@tux3 I'm still not *entirely* sure what you mean exactly, but I'm reasonably sure this will fix it. When enabling chat log encryption, an existing encrypted chat log that had previously been ignored is now tested with the password entered while enabling encryption (as opposed to just being overwritten previously).
