### ISSUE TITLE
False dilemna when trying to delete encrypted history

### ISSUE THREAD

**Issue by tux3** [dubslow/qTox#7]
![image3](https://cloud.githubusercontent.com/assets/5155966/5882281/4fa5c280-a348-11e4-851e-4be36fee12bb.jpg)

This message box lets you choose between "No" and "Cancel". Clicking No does delete history.
It should probably be Yes/No or Yes/Cancel

**Comment by dubslow** [comment]
Err... typo on my part, when coding apparently...
